### ISSUE TITLE
Question about dataset

### ISSUE THREAD

**Issue by ShuaibZyx** [CharlieCrosley/Polygen-Pytorch#1]
Hello! I would like to ask what the format of the input data set looks like when using categories, image inference polygons? What should the data set include? Thank you very much for your answer, I am new to this field. Thnks again.

**Comment by CharlieCrosley** [comment]
> Hello! I would like to ask what the format of the input data set looks like when using categories, image inference polygons? What should the data set include? Thank you very much for your answer, I am new to this field. Thnks again.

Hello, sorry for not making this clearer. The input data for image + class label inference should be a dictionary with keys "image" that is a 256x256 greyscale image and "class_label" which is an integer. An example of this is in the singleview_reconstruction_inference.ipynb file where you can print the "inp" variable to see the input data. It's important to note that, when using a custom input image, the code to mask the background to black in the "get_image" function must be changed as it currently assumes a constant background colour.

**Comment by ShuaibZyx** [comment]
Thank you very much for your answer. It helps me a lot. I read your suggestions carefully and tried to use blender to generate a rendered image of the model, but I tried for a long time without success. Can you share the data set you used? I want to see the format so that I can make new data sets. I really have a lot of questions to ask about Polygen model, but many people haven't replied to me when I asked them online. I would like to ask you for advice humbly. Would you like to make friends with me? My email is 2631667689@qq.com, or I can download any other social software you commonly use. Anyway, thanks for your kind and generous answers.
